### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by Jos512** [rdwatters/hugo-docs-concept#103]
I just forked the repo with the idea of exploring the content to see if I can make contributions. What are the guidelines/instructions for contribution?

I'm asking because I get an awful lot of errors when building the forked repo:

```
 I:\Hugodocs\hugo-docs-concept>hugo server -D
Started building sites ...
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:28 Two or more menu items have the same name/identifier in Menu "main": "Overview".
Rename or set an unique identifier.
ERROR 2017/04/28 08:47:49 Failed to get json resource https://api.instagram.com/oembed/?url=https://instagram.com/p/BMokmydjG-M/&hidecaption=1 with error messa
ge Get https://api.instagram.com/oembed/?url=https://instagram.com/p/BMokmydjG-M/&hidecaption=1: dial tcp 10.20.30.42:443: connectex: A connection attempt fail
ed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
ERROR 2017/04/28 08:48:10 Failed to get json resource https://api.twitter.com/1/statuses/oembed.json?id=666616452582129664 with error message Get https://api.t
witter.com/1/statuses/oembed.json?id=666616452582129664: dial tcp 10.20.30.42:443: connectex: A connection attempt failed because the connected party did not p
roperly respond after a period of time, or established connection failed because connected host has failed to respond.
panic: reflect: Zero(nil) [recovered]
        panic: reflect: Zero(nil)
goroutine 313 [running]:
text/template.errRecover(0xc0420317d0)
        /usr/local/go/src/text/template/exec.go:146 +0x69
panic(0xaaccc0, 0xc04804ab20)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
reflect.Zero(0x0, 0x0, 0x0, 0xaceda0, 0xc04687e8e8)
        /usr/local/go/src/reflect/value.go:2122 +0x13b
text/template.(*state).validateType(0xc042031750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbc4ee8)
        /usr/local/go/src/text/template/exec.go:697 +0x707
text/template.(*state).evalArg(0xc042031750, 0xb0d1a0, 0xc043a63680, 0x16, 0x0, 0x0, 0xedf340, 0xc0422279f0, 0xc04218b710, 0x80000c0472c4580, ...)
        /usr/local/go/src/text/template/exec.go:746 +0x877
text/template.(*state).evalChainNode(0xc042031750, 0xb0d1a0, 0xc043a63680, 0x16, 0xc04200bc00, 0xc042142e90, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/text/template/exec.go:502 +0xf9
text/template.(*state).evalCommand(0xc042031750, 0xb0d1a0, 0xc043a63680, 0x16, 0xc04218b5c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/text/template/exec.go:430 +0x5fa
text/template.(*state).evalPipeline(0xc042031750, 0xb0d1a0, 0xc043a63680, 0x16, 0xc0422279a0, 0x40f97c, 0xc04687e7e0, 0x30)
        /usr/local/go/src/text/template/exec.go:406 +0xf9
text/template.(*state).walk(0xc042031750, 0xb0d1a0, 0xc043a63680, 0x16, 0xedeec0, 0xc04218b740)
        /usr/local/go/src/text/template/exec.go:232 +0x561
text/template.(*state).walk(0xc042031750, 0xb0d1a0, 0xc043a63680, 0x16, 0xedf220, 0xc04218b590)
        /usr/local/go/src/text/template/exec.go:240 +0x140
text/template.(*Template).execute(0xc04200ad00, 0xed4f60, 0xc049faa690, 0xb0d1a0, 0xc043a63680, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:195 +0x211
text/template.(*Template).Execute(0xc04200ad00, 0xed4f60, 0xc049faa690, 0xb0d1a0, 0xc043a63680, 0xc0499e4bb0, 0xb10120)
        /usr/local/go/src/text/template/exec.go:178 +0x5a
html/template.(*Template).Execute(0xc04218b530, 0xed4f60, 0xc049faa690, 0xb0d1a0, 0xc043a63680, 0xc042031880, 0xc042044400)
        /usr/local/go/src/html/template/template.go:120 +0x93
github.com/spf13/hugo/tpl.(*TemplateAdapter).Execute(0xc04805e280, 0xed4f60, 0xc049faa690, 0xb0d1a0, 0xc043a63680, 0x40, 0xb40320)
        <autogenerated>:3 +0x7c
github.com/spf13/hugo/hugolib.renderShortcodeWithPage(0xed9120, 0xc04805e280, 0xc043a63680, 0x0, 0x0)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/shortcode.go:586 +0xda
github.com/spf13/hugo/hugolib.renderShortcode(0xc0484781a8, 0x5, 0x0, 0x0, 0x0, 0xaa41c0, 0xc0484de060, 0x0, 0x0, 0x0, ...)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/shortcode.go:278 +0x5db
github.com/spf13/hugo/hugolib.renderShortcodes.func1(0xc042031d20, 0xc049c39830, 0xc042031ce0, 0xc049d9b408)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/shortcode.go:320 +0x55
github.com/spf13/hugo/hugolib.executeShortcodeFuncMap(0xc0484808d0, 0xba6985, 0x1b, 0xc042031e40)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/shortcode.go:301 +0xec
github.com/spf13/hugo/hugolib.handleShortcodes(0xc045e63400, 0xc049cdc800, 0x3853, 0x44e4, 0xc049d38d80, 0xca6, 0xc049d38000, 0xca6, 0xd80)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/hugo_sites.go:588 +0x1ae
github.com/spf13/hugo/hugolib.(*Site).preparePagesForRender.func1(0xc046cb56a0, 0xc0421106c0, 0xc049531da0, 0xc049533320)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/hugo_sites.go:536 +0x14c
created by github.com/spf13/hugo/hugolib.(*Site).preparePagesForRender
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/hugo_sites.go:567 +0xdd
```

**Edit**: I "fixed" the errors by removing all references to Twitter and Instagram in the `shortcodes.md` file, so that Hugo does not fail anymore when having trouble reaching those domains. 

Can I safely ignore the menu warnings?

**Comment by rdwatters** [comment]
@Jos512 Thanks for reporting this issue. I apologize for the delayed response. As you've probably already noticed, an issue was opened up in the main repo for Hugo for panic warnings when running the local server but working offline.

That said, you are more than welcome to make any existing changes to copy/content and submit a PR. I get the same warnings for the menu, _but_ the site still renders for me on localhost:1313...so not to worry.

I have written a separate contributions guideline just for documentation, btw. You can find it on the published site:

https://hugodocs.info/contribute/documentation/

I've also (temporarily) modified the docs concept `config.toml` so that the ["Places to Start" section](https://hugodocs.info/contribute/documentation/#places-to-start) points to this temporary repository (i.e. the repo for rdwatters; this will hopefully be merged soon into the actual Hugo repo) for files that have already been identified as "needing examples."

As an FYI, @budparr is working on a pretty fantastic new theme for the docs (i.e., this version of the docs), so please don't let visual styling influence any content or copy changes you'd like to make. Closing this issue for now.

Thanks!
